/*
 * Copyright (c) 2026, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.nvidia.spark.rapids.delta

import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * Marks a Delta relation whose file-relative row-index column must be generated by the GPU reader.
 * Only a small opaque ID is placed in the logical relation and it is resolved on the driver when
 * the file format is converted.
 */
object GpuLowShuffleMergeScanRegistry {
  val OPTION_KEY: String = "spark.rapids.internal.delta.lowShuffleMerge.scanId"

  private val scans = new ConcurrentHashMap[String, java.lang.Boolean]()

  def register(): String = {
    val id = UUID.randomUUID().toString
    scans.put(id, java.lang.Boolean.TRUE)
    id
  }

  def contains(options: Map[String, String]): Boolean =
    options.get(OPTION_KEY).exists(scans.containsKey)

  def remove(id: String): Unit = scans.remove(id)
}
